### ISSUE TITLE
How to find Auth Token?

### ISSUE THREAD

**Issue by rb1111-1** [bzellman/WindmillAC#11]
I'm having a little trouble. The Auth Token is not available on Windmill Air app under Devices, or on their site. Any ideas where I might be able to find it? Thanks!

**Comment by RyanSylvestre** [comment]
You can go to https://dashboard.windmillair.com on a desktop browser and it should exist in the table. It's a little annoying to copy/paste the Auth Token, I think I ended up using browser devtools to do so.

**Comment by rb1111-1** [comment]
Thank you! This worked. A new issue has cropped up on HA 2024.7.3, will post a new issue.

**Comment by rb1111-1** [comment]
Adding one more comment here to say that "Reader View" in Safari makes it very easy to copy the Auth Token.

I resolved my other issue on my own. Thanks!
